version: "3.3"

services:
  app:
    build: ./app
    container_name: shiftapp
    command: ["npm", "start"]
    volumes:
      - ./app:/home/node/app
    networks:
      - shiftnet
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./api
    container_name: shiftapi
    command: ["npm", "run", "dev"]
    volumes:
      - ./api:/home/node/api
    networks:
      - shiftnet
    ports:
      - "3031:3031"
    links:
      - db
    depends_on:
      - db

  db:
    image: neo4j:3.3.0
    container_name: shiftn4j
    environment:
      - NEO4J_AUTH=neo4j/Shift!007
    networks:
      - shiftnet
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./db/data:/data"
      - "./db/logs:/logs"

networks:
  shiftnet:
